#    C++ Examples - a collection of C++ examples intended to serve as a tutorial
#    Copyright (C) 2011 Alejandro Cabrera
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
top = '.'
out = 'build'
APPNAME = 'c++-examples'
VERSION = 0.3

import os

CXXFLAGS = ['-Wall','-Wextra','-ansi','-pedantic','-std=c++0x']

def try_file(ctx, file_name):
	def_name = ('HAS_' + os.path.basename(file_name).replace('.cpp', '')).upper()
	data = ""
	with open(file_name, "r") as f:
		data = f.readlines()
	ctx.check_cxx(fragment=''.join(data), define_name=def_name,
                      msg = "checking for: " + def_name, 
                      cxxflags='-std=c++0x', mandatory=False)

def options(opt):
	opt.load('compiler_cxx')

def configure(ctx):
	path = os.path.join(ctx.path.abspath(), 'tests')
	ctx.load('compiler_cxx')
	[try_file(ctx,os.path.join(path,x)) for x in os.listdir(path) if x.endswith('.cpp')]
	ctx.write_config_header('config.h')
	
def build(bld):
	path = bld.path.abspath()
	for source in [x for x in os.listdir(path) if x.endswith('.cpp')]:
		bld.program(
			source = source,
			target = source.split('.')[0],
			cxxflags = CXXFLAGS
		)
