CXXFLAGS = ['-Wall', '-Wextra', '-std=c++0x']

def options(ctx):
  ctx.load('compiler_cxx')

def configure(ctx):
  ctx.load('compiler_cxx')

def build(bld):
  bld.program(source='policy.cpp',
              target='policy',
              cxxflags=CXXFLAGS)
