#    C++ Examples - a collection of C++ examples intended to serve as a tutorial
#    Copyright (C) 2011-2012 Alejandro Cabrera
# 
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
# 
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
# 
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>. 
top = '.'
out = 'build'
APPNAME = 'c++-examples-algorithms'
VERSION = 0.3

import os

CXXFLAGS = ['-Wall','-Wextra','-ansi','-pedantic','-std=c++0x']

def options(opt):
	opt.load('compiler_cxx')

def configure(ctx):
	ctx.load('compiler_cxx')
	
def build(bld):
	path = bld.path.abspath()
	for source in [x for x in os.listdir(path) if x.endswith('.cpp')]:
		bld.program(
			source = source,
			target = source.split('.')[0],
			cxxflags = CXXFLAGS
		)
