import os

CXXFLAGS = ['-Wall', '-Wextra', '-std=c++0x']

def options(ctx):
  ctx.load('compiler_cxx')

def configure(ctx):
  ctx.load('compiler_cxx')

def build(bld):
  base = bld.path.abspath()
  bld.shlib(source=[os.path.join(base, 'include','detail', x) for x in os.listdir(base + '/include/detail')],
            includes=base + '/include',
            target=base + '/factorial',
            cxxflags=CXXFLAGS)

  bld.program(source=base + '/src/test.cpp',
              includes=base + '/include',
              use=base + '/factorial',
              target='dynamic_pimpl',
              cxxflags=CXXFLAGS)
